---
output:
  pdf_document:
    number_sections: true
    keep_tex: true
    extra_dependencies: rotating
  title: "models"
  author: "Hubert Cadieux, Alexis Bibeau"
  date: "2022-11-02"
  graphics: yes
  fig_caption: yes
  header-includes:
    \usepackage{lscape}
    \usepackage{rotating}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

responsability -> Les citoyens ordinaires, et pas seulement les autorités et les décideurs, ont une grande part de responsabilité à l'égard de l'environnement

```{r echo=F, message=F}
library(stargazer)
library(tidyverse)
setwd("..")
Data <- readRDS("_SharedFolder_quorum-enviro/data/cleanData/data.rds") %>%
  mutate(educ_level = ifelse(ses_educBHS == 1, 0, NA),
         educ_level = ifelse(ses_educCollege == 1, 0.5,
                             educ_level),
         educ_level = ifelse(ses_educUniv == 1, 1,
                             educ_level),
         responsability = responsability_citizensVsGvnt)
vds <- names(Data %>% 
               select(starts_with("radicalisation_tolerate")))
names(Data) <- gsub("radicalisation_tolerate_",
                    "",
                    names(Data))
vds <- gsub("radicalisation_tolerate_",
                    "",
                    vds)
attach(Data)
```


```{r echo=F, message=F}
for (i in 1:length(vds)){
  vd <- vds[i]
  modeli <- eval(parse(text = paste0("lm(", vd, " ~ scale_gravity + ses_gender_male +
                            ses_age + educ_level +
                 ses_incomeHigh + ses_incomeLow + responsability,
               data = Data)")))
  assign(vd, modeli)
}
```

```{r results='asis', echo=F, resize.width=1, align = "left"}
stargazer(vandalismObjects, throwingObjectsInfrastructure, sabotagingInfrastructure, violatingPowerful, fightPolice, blockBridgeRoad, header = F,
          single.row = F, column.sep.width = "1pt",
          no.space = TRUE, type = "latex",
          digits = 2, keep.stat = c("n", "rsq"),
          float.env = "sidewaystable",
          title="Sans interaction 1")
```

```{r results='asis', echo=F, resize.width=1, align = "left"}
stargazer(attachTreeVehicule, blockPipelineConstruction, occupyPublicSpace, manifestation, divest, boycott, signPetition,
          header = F,
          single.row = F, column.sep.width = "1pt",
          no.space = TRUE, type = "latex",
          digits = 2, keep.stat = c("n", "rsq"),
          float.env = "sidewaystable",
          title="Sans interaction 2")
```


```{r echo=F, message=F}
for (i in 1:length(vds)){
  vd <- vds[i]
  modeli <- eval(parse(text = paste0("lm(", vd, " ~ scale_gravity*ses_age + ses_gender_male +
                             responsability + educ_level +
                 ses_incomeHigh + ses_incomeLow,
               data = Data)")))
  assign(vd, modeli)
}
```

```{r results='asis', echo=F, resize.width=1, align = "left"}
stargazer(vandalismObjects, throwingObjectsInfrastructure, sabotagingInfrastructure, violatingPowerful, fightPolice, blockBridgeRoad, header = F,
          single.row = F, column.sep.width = "1pt",
          no.space = TRUE, type = "latex",
          digits = 2, keep.stat = c("n", "rsq"),
          float.env = "sidewaystable",
          title="Interaction âge-préoccupations 1")
```

```{r results='asis', echo=F, resize.width=1, align = "left"}
stargazer(attachTreeVehicule, blockPipelineConstruction, occupyPublicSpace, manifestation, divest, boycott, signPetition,
          header = F,
          single.row = F, column.sep.width = "1pt",
          no.space = TRUE, type = "latex",
          digits = 2, keep.stat = c("n", "rsq"),
          float.env = "sidewaystable",
          title="Interaction âge-préoccupations 2")
```


```{r echo=F, message=F}
for (i in 1:length(vds)){
  vd <- vds[i]
  modeli <- eval(parse(text = paste0("lm(", vd, " ~ scale_gravity*ses_incomeLow + ses_gender_male +
                            ses_age + educ_level +
                 ses_incomeHigh + responsability,
               data = Data)")))
  assign(vd, modeli)
}
```

```{r results='asis', echo=F, resize.width=1, align = "left"}
stargazer(vandalismObjects, throwingObjectsInfrastructure, sabotagingInfrastructure, violatingPowerful, fightPolice, blockBridgeRoad, header = F,
          single.row = F, column.sep.width = "1pt",
          no.space = TRUE, type = "latex",
          digits = 2, keep.stat = c("n", "rsq"),
          float.env = "sidewaystable",
          title="Interaction pauvreté-préoccupations 1")
```

```{r results='asis', echo=F, resize.width=1, align = "left"}
stargazer(attachTreeVehicule, blockPipelineConstruction, occupyPublicSpace, manifestation, divest, boycott, signPetition,
          header = F,
          single.row = F, column.sep.width = "1pt",
          no.space = TRUE, type = "latex",
          digits = 2, keep.stat = c("n", "rsq"),
          float.env = "sidewaystable",
          title="Interaction pauvreté-préoccupations 2")
```


```{r echo=F, message=F}
for (i in 1:length(vds)){
  vd <- vds[i]
  modeli <- eval(parse(text = paste0("lm(", vd, " ~ scale_gravity*responsability + ses_gender_male +
                            ses_age + educ_level +
                 ses_incomeHigh + ses_incomeLow,
               data = Data)")))
  assign(vd, modeli)
}
```

```{r results='asis', echo=F, resize.width=1, align = "left"}
stargazer(vandalismObjects, throwingObjectsInfrastructure, sabotagingInfrastructure, violatingPowerful, fightPolice, blockBridgeRoad, header = F,
          single.row = F, column.sep.width = "1pt",
          no.space = TRUE, type = "latex",
          digits = 2, keep.stat = c("n", "rsq"),
          float.env = "sidewaystable",
          title="Interaction responsabilité des citoyens-préoccupations 1")
```

```{r results='asis', echo=F, resize.width=1, align = "left"}
stargazer(attachTreeVehicule, blockPipelineConstruction, occupyPublicSpace, manifestation, divest, boycott, signPetition,
          header = F,
          single.row = F, column.sep.width = "1pt",
          no.space = TRUE, type = "latex",
          digits = 2, keep.stat = c("n", "rsq"),
          float.env = "sidewaystable",
          title="Interaction responsabilité des citoyens-préoccupations 2")
```